In [1]:
%run 'Initialization.ipynb'
%run 'Functions.ipynb'

6040
['2', 'M', '56', '16', '70072']
3883
['1', 'Toy Story', "Animation|Children's|Comedy", '1995']
(3884L, 6041L)
98742
[594, 1]
(3884L, 6041L)
69
3883
3
0
0
5
1
18
(3884L, 19L)
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.]
2.91547594742
(3884L, 6041L)
([3, 45, 7, 2], [2, 54, 13, 15], 0.97228425171235)


In [11]:
similiarity = np.array([[0.0 for i in range(len(users)+1)] for j in range(len(users)+1)])
print similiarity.shape

(6041L, 6041L)


In [ ]:
#Calculating similarity for all users with all other users
counti=0
for i in np.transpose(training_ratings):
    countj=0
    if(np.all(i==0)==False):
        for j in np.transpose(training_ratings):
            if((np.all(j==0)==False) and countj>=counti):
                similiarity[counti,countj]=cosine_similarity(i,j)
            countj+=1
    print counti
    counti+=1

In [13]:
np.savetxt('similiarity.txt', similiarity,fmt='%1.3f', delimiter=',')

In [2]:
lines = [line.rstrip('\n') for line in open('similiarity.txt')]
final_ratings=[]
for i in lines:
    temp=i.split(',')
    temp = map(float, temp)
    final_ratings.append(temp)
sim=np.asarray(final_ratings)

In [3]:
sim[17][81]

0.14899999999999999

In [4]:
cosine_similarity(np.transpose(training_ratings)[1],np.transpose(training_ratings)[6])

0.12892345209204648

In [5]:
for i in reversed(range(len(sim))):
    for j in range(len(sim)):
        if j>i:
            sim[j][i]=sim[i][j]
        if i==j:
            sim[j][i]=0

In [6]:
sim[81][17]

0.14899999999999999

In [7]:
sim

array([[ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.093, ...,  0.   ,  0.165,  0.115],
       [ 0.   ,  0.093,  0.   , ...,  0.069,  0.063,  0.196],
       ..., 
       [ 0.   ,  0.   ,  0.069, ...,  0.   ,  0.145,  0.074],
       [ 0.   ,  0.165,  0.063, ...,  0.145,  0.   ,  0.194],
       [ 0.   ,  0.115,  0.196, ...,  0.074,  0.194,  0.   ]])

In [8]:
sim_max = np.array([[0 for i in range(20)] for j in range(len(users)+1)])
print sim_max.shape

(6041L, 20L)


In [9]:
np.argsort(sim[1])[-20:]

array([2566,  681, 1850, 1858, 2796, 2083, 1415, 1283, 1744,   96, 5975,
       1506, 5920, 5705, 1359,  626, 5762, 5343, 5190, 1481], dtype=int64)

In [10]:
for i in range(len(sim)):
    sim_max[i]=np.fliplr([np.argsort(sim[i])[-20:]])[0]

In [11]:
sim_max[1]

array([1481, 5190, 5343, 5762,  626, 1359, 5705, 5920, 1506, 5975,   96,
       1744, 1283, 1415, 2083, 2796, 1858, 1850,  681, 2566])

In [12]:
sim[1][1481]

0.33500000000000002

In [13]:
len(np.nonzero(training_ratings[1])[0])

1873

In [17]:
sim_ratings = np.array([[0.0 for i in range(len(users)+1)] for j in range(len(movies)+1)])
sim_ratings=np.copy(training_ratings)
sim_ratings.shape

(3884L, 6041L)

In [18]:
# count=0
# for z in range(len(training_ratings[1])):
#     for i in range(len(sim_max[z])):
#         for j in range(len(sim_ratings[:,1])):
#             if(sim_ratings[j][z]==0 and training_ratings[j][sim_max[z][i]]!=0):
#                 count+=1
#                 sim_ratings[j][z]=training_ratings[j][sim_max[z][i]]
# print count

#Finding average similiar Ratings for 20 similiar users
count=0
for z in range(len(training_ratings[1])):
    if z!=0:
        temp = np.array([0.0 for i in range(len(movies)+1)])
        for j in range(len(sim_ratings[:,1])):
            for i in range(len(sim_max[z])):
                temp[j]+=training_ratings[j][sim_max[z][i]]*sim[z][sim_max[z][i]]
        norm=0
        for i in range(len(sim_max[1])):
            norm+=sim[z][sim_max[z][i]]
        for j in range(len(sim_ratings[:,1])):
            if(sim_ratings[j][z]==0 and temp[j]!=0):
                count+=1
                sim_ratings[j][z]=temp[j]/norm
print count

6301240


In [19]:
print len(np.nonzero(training_ratings[:,1])[0])
print len(np.nonzero(sim_ratings[:,1])[0])

47
102


In [20]:
sim_ratings[:,1]

array([0, 3, 0, ..., 0, 0, 0])

In [21]:
print calcRMSE(sim_ratings,validation_ratings,validation_matrix)

2.73543805942


In [ ]:
1.45713777357 without similiarity 6302049 
2.73543805942 with similiarity 6301240 