In [1]:
%run 'Initialization.ipynb'
%run 'Functions.ipynb'

6040
['2', 'M', '56', '16', '70072']
3883
['1', 'Toy Story', "Animation|Children's|Comedy", '1995']
(3884L, 6041L)
98742
[594, 1]
(3884L, 6041L)
69
3883
3
0
0
5
1
18
(3884L, 19L)
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.]
2.91547594742
(3884L, 6041L)


In [37]:
full_ratings=getFinalRatings()

In [38]:
full_ratings.shape

(3884L, 6041L)

In [39]:
validation_ratings_full= np.array([[0.0 for i in range(len(full_ratings[0]))] for j in range(len(full_ratings))])
training_ratings_full=np.copy(full_ratings)

In [40]:
training_ratings_full.shape

(3884L, 6041L)

In [41]:
#Generating training and testing matrix
validation_matrix_full=[]
for i in range(len(training_ratings_full)):
    for j in range(len(training_ratings_full)*len(training_ratings_full[0])/(len(users)*10)):
        col=int(random.random()*10000)%len(movies)
        validation_ratings_full[i][col]=training_ratings_full[i][col]
        training_ratings_full[i][col]=0
        if i!=0:
            validation_matrix_full.append([i,col])

In [125]:
#np.nonzero(validation_ratings_full[1])

In [43]:
training_ratings_full[1][3754]

4.2000000000000002

In [44]:
validation_matrix_full[1]

[1, 2065]

In [45]:
full_ratings[1][3754]

4.2000000000000002

In [46]:
validation_ratings_full[1][3754]

0.0

In [120]:
initial_model_parameter=np.array([[0.0 for i in range(len(movie_types)+1)] for j in range(len(users)+1)])
print initial_model_parameter.shape

(6041L, 19L)


In [48]:
initial_model_parameter[1]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.])

In [50]:
training_ratings_full[:,1]

array([ 1.06,  4.34,  3.51, ...,  2.45,  3.4 ,  2.77])

In [64]:
training_ratings_full[1035][1]

4.1600000000000001

In [71]:
for m in movies:
    if int(m[0])<=len(movies):
        movies_genre_array[m[0],0]=1
        genre_list=m[2].split("|")
        for t in m[2].split("|"):
            index=movie_types.get(t)
            movies_genre_array[m[0],index]=1
movies_genre_array.shape

(3884L, 19L)

In [121]:
#Calculating model parameters
for j in range(len(training_ratings_full[1])):
    if j!=0:
        for i in range(len(training_ratings_full[:,j])):
            if i!=0:
                initial_model_parameter[j]=initial_model_parameter[j]+movies_genre_array[i]*training_ratings_full[i][j]
        initial_model_parameter[j][0]=0
        val=sum(initial_model_parameter[j])
        initial_model_parameter[j]=initial_model_parameter[j]/val
initial_model_parameter[1]

array([ 0.        ,  0.0774953 ,  0.04421038,  0.01860492,  0.03913183,
        0.18130657,  0.03319489,  0.01935561,  0.24936116,  0.01060933,
        0.00826242,  0.04466369,  0.01890658,  0.0184297 ,  0.07868536,
        0.04083415,  0.0794607 ,  0.02548919,  0.01199819])

In [122]:
np.amax(initial_model_parameter[1])

0.24936116265449826

In [123]:
initial_model_parameter[1][8]

0.24936116265449826